changes/views.py
import os
import json
import itertools
from collections import OrderedDict

from flask import request, current_app, Blueprint, render_template
from sqlalchemy import text

from changes.database import engine

views = Blueprint('views', __name__)

@views.route('/')
def index():
    limit = request.args.get('limit', 100)
    offset = request.args.get('offset', 0)
    records = '''
        SELECT
          id AS "Record ID",
          case_number AS "Case Number",
          orig_date AS "Report Date",
          block AS "Block",
          iucr AS "IUCR Code",
          primary_type "Primary Classification",
          description AS "Secondary Classification",
          location_description AS "Location Description",
          arrest AS "Arrest",
          domestic AS "Domestic",
          beat AS "Beat",
          district AS "District",
          ward AS "Ward",
          community_area AS "Community Area",
          fbi_code AS "FBI Code",
          x_coordinate AS "X Coordinate",
          y_coordinate AS "Y Coordinate",
          year AS "Year",
          updated_on AS "Last Update",
          latitude AS "Latitude",
          longitude AS "Longitude"
        FROM changed_records
        ORDER BY id
        LIMIT :limit
    '''
    display_fields = [
        "Record ID",
        "Case Number",
        "Report Date",
        "Block",
        "Primary Classification",
        "Secondary Classification",
        "Location Description",
        "Arrest",
        "Last Update",
    ]

    if request.args.get('page'):
        page = int(request.args['page'])
        offset = (page - 1) * 100
        records = '{0} OFFSET {1}'\
                .format(records, offset)

    records = engine.execute(text(records),
                             limit=limit,
                             offset=offset)

    grouped_records = []
    fields = set()
    for record_id, group in itertools.groupby(records, key=lambda x: x['Record ID']):

        group = list(group)
        grouped_by_field = {}
        for record in group:
            for field in record.keys():
                try:
                    grouped_by_field[field].append(record[field])
                except KeyError:
                    grouped_by_field[field] = [record[field]]

        diff_fields = []
        output_record = OrderedDict()

        for field, values in grouped_by_field.items():
            if len(set(values)) > 1:
                diff_fields.append(field)

            if field in display_fields:
                fields.add(field)
                output_record[field] = max(t for t in grouped_by_field[field] if t is not None)

        output_record['diff_fields'] = diff_fields
        output_record['Change Count'] = len(group)
        grouped_records.append(output_record)

    record_count = '''
        SELECT COUNT(DISTINCT id) AS record_count
        FROM changed_records
    '''

    record_count = engine.execute(record_count).first().record_count

    page_count = int(round(record_count, -2) / 100)

    return render_template('index.html',
                           grouped_records=grouped_records,
                           page_count=page_count,
                           fields=fields)

@views.route('/detail/<record_id>/')
def detail(record_id):
    record_set = '''
        SELECT
          id AS "Record ID",
          case_number AS "Case Number",
          orig_date AS "Report Date",
          block AS "Block",
          c.iucr AS "IUCR Code",
          CASE WHEN index_code = 'I'
          THEN 'Yes'
          ELSE 'No'
          END AS "Index crime?",
          primary_type "Primary Classification",
          description AS "Secondary Classification",
          location_description AS "Location Description",
          arrest AS "Arrest",
          domestic AS "Domestic",
          beat AS "Beat",
          district AS "District",
          ward AS "Ward",
          community_area AS "Community Area",
          fbi_code AS "FBI Code",
          x_coordinate AS "X Coordinate",
          y_coordinate AS "Y Coordinate",
          year AS "Year",
          updated_on AS "Last Update",
          latitude AS "Latitude",
          longitude AS "Longitude"
        FROM changed_records AS c
        JOIN iucr AS i
        ON c.iucr = i.iucr
        WHERE id = :record_id
        ORDER BY updated_on
    '''
    record_set = engine.execute(text(record_set), record_id=record_id)

    grouped_by_field = OrderedDict()

    for record in record_set:
        for field in record.keys():
            try:
                grouped_by_field[field].append(getattr(record, field))
            except KeyError:
                grouped_by_field[field] = [getattr(record, field)]

    diff_fields = []

    for field, values in grouped_by_field.items():
        if len(set(values)) > 1:
            diff_fields.append(field)
    return render_template('detail.html',
                           grouped_by_field=grouped_by_field,
                           diff_fields=diff_fields)


@views.route('/deleted/')
def deleted():
    return render_template('index.html',
                           grouped_records=grouped_records,
                           page_count=page_count,
                           fields=fields)


@views.route('/downgraded/')
def downgraded():

    limit = request.args.get('limit', 100)
    offset = request.args.get('offset', 0)

    subquery = '''
      SELECT
        id,
        c.iucr,
        c.primary_type || ' - ' || c.description AS description,
        c.fbi_code,
        index_code,
        updated_on
      FROM changed_records AS c
      JOIN iucr AS i
        USING(iucr)
      JOIN (
        SELECT
          id,
          array_agg(index_code)
        FROM changed_records
        JOIN iucr
          USING(iucr)
        GROUP BY id
        HAVING(
          array_length(array_agg(DISTINCT index_code), 1) > 1
            AND array_agg(index_code) && ARRAY['I', 'N']::VARCHAR[]
        )
      ) AS s
        USING(id)
      ORDER BY id
    '''

    query = '''
      SELECT
        id,
        json_agg(row_to_json(s.*)) AS data
      FROM ({}) AS s
      GROUP BY id
      LIMIT :limit
    '''.format(subquery)

    if request.args.get('page'):
        page = int(request.args['page'])
        offset = (page - 1) * 100
        query = '{0} OFFSET {1}'\
                .format(query, offset)

    records = engine.execute(text(query),
                             limit=limit,
                             offset=offset)

    page_count = '''
      SELECT COUNT(DISTINCT id) FROM ({}) AS s
    '''.format(subquery)

    page_count = engine.execute(text(page_count)).first().count

    return render_template('downgraded.html',
                           records=records,
                           page_count=page_count)

changes/templates/base.html
<!DOCTYPE html>
<html lang="en" style="height: 100%;">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap.yeti.min.css') }}" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block extra_styles %}{% endblock %}
    <link href="{{ url_for('static', filename='css/custom.css') }}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="static/js/html5shiv.js"></script>
      <script src="static/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body style="height: 100%">
      <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Ch-ch-ch-changes</a>
        </div>
        <div class="navbar-collapse collapse pull-right">
          <ul class="nav navbar-nav">
            {#
            <li class="{% if request.path == url_for('views.upload') %}active{% endif %}"><a href='{{ url_for('views.upload') }}'>Get started!</a></li>
            <li class="{% if request.path == url_for('views.data_sources') %}active{% endif %}"><a href='{{ url_for('views.data_sources') }}'>Data sources</a></li>
            <li class="{% if request.path == url_for('views.geographies') %}active{% endif %}"><a href='{{ url_for('views.geographies') }}'>Geographies</a></li>
            <li class="{% if request.path == url_for('views.contribute_data') %}active{% endif %}"><a href='{{ url_for('views.contribute_data') }}'>Contribute source</a></li>
            <li class="{% if request.path == url_for('views.about') %}active{% endif %}"><a href='{{ url_for('views.about') }}'>About</a></li>
            #}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
      <div class="container">
        {% block content %}{% endblock %}

        <br />
        <div class='clearfix'></div>

        <div class="footer">
          <p class='pull-right'>
          </p>
        </div>
      </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ url_for('static', filename='js/jquery-1.10.1.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

    <script src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
    {% block extra_javascript %}{% endblock %}

  </body>
</html>

changes/templates/downgraded.html
{% extends 'base.html' %}
{% from 'macros.html' import pager %}
{% block title %}Ch-ch-ch-changes{% endblock %}
{% block extra_styles %}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th>Record ID</th>
                    <th>IUCR code</th>
                    <th>FBI Code</th>
                    <th>Description</th>
                    <th>Updated On</th>
                </tr>
            </thead>
            <tbody>
            {% for record in records %}
                {% set css_class = loop.cycle('danger', '') %}
                <tr class="{{ css_class }}">
                    <td rowspan={{ record.data|length }}>
                      <a href="{{ url_for('views.detail', record_id=record.id ) }}">
                         {{ record.id }}
                      </a>
                    </td>
                    <td>{{ record.data[0].iucr }}</td>
                    <td>
                        {{ record.data[0].fbi_code }} ({% if record.data[0].index_code == 'I' %}Index{% else %}Non-Index{% endif %})
                    </td>
                    <td>{{ record.data[0].description }}</td>
                    <td>{{ record.data[0].updated_on }}</td>
                </tr>
                {% for data in record.data[1:] %}
                    <tr class="{{ css_class }}">
                        <td>{{ data.iucr }}</td>
                        <td>
                            {{ data.fbi_code }} ({% if data.index_code == 'I' %}Index{% else %}Non-Index{% endif %})
                        </td>
                        <td>{{ data.description }}</td>
                        <td>{{ data.updated_on }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
      {{ pager(request.args.get('page', 1)|int, page_count|int, request.path) }}
    </div>
</div>
{% endblock %}
{% block extra_javascript %}{% endblock %}

changes/templates/index.html
{% extends 'base.html' %}
{% from 'macros.html' import pager %}
{% block title %}Ch-ch-ch-changes{% endblock %}
{% block extra_styles %}{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th>Change Count</th>
                    {% for field in fields %}
                        {% if field != 'Change Count' %}
                            <th>{{ field }}</th>
                        {% endif %}
                    {% endfor %}
                    <th>Changed fields</th>
                </tr>
            </thead>
            <tbody>
                {% for record in grouped_records %}

                    {% if "IUCR Code" in record['diff_fields'] %}
                        <tr class="danger">
                    {% else %}
                        <tr>
                    {% endif %}
                        {% set record_id = record['Record ID'] %}
                        <td><a href="{{ url_for('views.detail', record_id=record_id ) }}">{{ record['Change Count'] }}</a></td>
                        {% for field in fields %}
                            {% if field != 'Change Count' %}
                                <td>{{ record[field] }}</td>
                            {% endif %}
                        {% endfor %}
                        <td>
                            {{ record['diff_fields']|join(', ') }}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
      {{ pager(request.args.get('page', 1)|int, page_count|int, request.path) }}
    </div>
</div>
{% endblock %}
{% block extra_javascript %}{% endblock %}

changes/templates/macros.html
{% macro pager(page, pages, url_base) -%}
{% if '?' in url_base %}
{% set url_base = url_base + '&' %}
{% else %}
{% set url_base = url_base + '?' %}
{% endif %}
{% if pages > 1 %}
<ul class="pagination">
    {% set min = page - 2 %}
    {% set max = page + 3 + 1 %}

    {% if min < 0 %}
        {% set max = max - min %}
    {% endif %}
    {% if max >= pages %}
        {% set min = min - max + pages %}
    {% endif %}

    {% if min <= 0 %}
        {% set min = 1 %}
    {% endif %}
    {% if max >= pages %}
        {% set max = pages %}
    {% endif %}

    {% if min > 1 %}
    <li>
        <a href="{{ url_base }}">&laquo;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&laquo;</a>
    </li>
    {% endif %}
    {% if page > 1 %}
    <li>
        <a href="{{ url_base }}page={{ page-1 }}">&lt;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&lt;</a>
    </li>
    {% endif %}

    {% for p in range(min, max) %}
    {% if page == p %}
    <li class="active">
        <a href="javascript:void(0)">{{ p }}</a>
    </li>
    {% else %}
    <li>
        <a href="{{ url_base }}page={{ p }}">{{ p }}</a>
    </li>
    {% endif %}
    {% endfor %}

    {% if page < pages %}
    <li>
        <a href="{{ url_base }}page={{ page + 1 }}">&gt;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&gt;</a>
    </li>
    {% endif %}
    {% if max < pages %}
    <li>
        <a href="{{ url_base }}page={{ pages }}">&raquo;</a>
    </li>
    {% else %}
    <li class="disabled">
        <a href="javascript:void(0)">&raquo;</a>
    </li>
    {% endif %}
</ul>
{% endif %}
{%- endmacro %}